apiVersion: v1
kind: Pod
metadata:
  namespace: default
  creationTimestamp: null
  labels:
    run: adapter
  name: adapter
spec:
  volumes:
  - name: logs-adapter
    emptyDir: {}
  initContainers:
  - name: transformer
    image: busybox:1.36.1
    restartPolicy: Always
    command: ['sh', '-c', 'sleep 20; while true; do while read LINE; do echo "$LINE" | cut -f2 -d"|" >> $(date +%Y-%m-%d-%H-%M-%S)-transformed.txt; done < /var/logs/diskspace.txt; sleep 20; done;']
    volumeMounts:
      - name: logs-adapter
        mountPath: /var/logs
  containers:
  - command:
    name: adapter
    command: ['sh', '-c', 'while true; do echo "$(date) | $(du -sh ~)" >> /var/logs/diskspace.txt; sleep5; done;']
    image: busybox:1.36.1
    resources: {}
    volumeMounts:
      - name: logs-adapter
        mountPath: /var/logs
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
