apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: my-lab
spec: {}
status: {}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: current-date
  namespace: my-lab
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: current-date
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - |
              echo "Current date: $(date)"
            image: busybox
            name: current-date
            resources: {}
          restartPolicy: Never
  schedule: '*/1 * * * *'
status: {}  
