apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: h92
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-run
  name: nginx-run
  namespace: h92
spec:
  containers:
  - image: nginx:1.21.6
    name: nginx-run
    securityContext:
      readOnlyRootFilesystem: true
    resources: {}
    volumeMounts:
    - name: nginx-run
      mountPath: /var/run
    - name: nginx-cache
      mountPath: /var/cache/nginx
    - name: nginx-data
      mountPath: /usr/local/nginx
  dnsPolicy: ClusterFirst
  volumes:
  - name: nginx-run
    emptyDir: {}
  - name: nginx-cache
    emptyDir: {}
  - name: nginx-data
    emptyDir: {}
  restartPolicy: Always
status: {}
