apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: debugbox
  name: debugbox
spec:
  containers:
  - command:
    - date 
    image: busybox
    name: debugbox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
