apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: v1
  annotations:
    description: this is pod nginx1
  name: nginx1
spec:
  containers:
  - image: nginx
    name: nginxc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: v2.1
  annotations:
    description: this is pod nginx2
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginxc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: v3
  annotations:
    description: this is pod nginx3
  name: nginx3
spec:
  containers:
  - image: nginx
    name: nginxc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
