apiVersion: v1
kind: Pod
metadata:
  name: customerservice1
spec:
  containers:
  - name: nginxc1
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: kcontrol 
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
