apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: statevar
  name: statevar
spec:
  containers:
  - env:
    - name: var1
      value: state1
    image: nginx
    name: statevar
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
