---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: test-space
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: space-pod
  name: space-pod
  namespace: test-space
spec:
  containers:
  - image: nginx
    name: space-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
