apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sensors
  name: sensors
spec:
  containers:
  - image: nginx
    name: sensors
    resources: {}
    env:
    - name: SENSORS_KEY
      valueFrom:
        configMapKeyRef:
          name: sensors
          key: var1
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
