apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sensor2
  name: sensor2
spec:
  containers:
  - image: nginx
    name: sensor
    envFrom:
    - configMapRef:
        name: sensors2
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
