apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: echojob
spec:
  completions: 3
  parallelism: 2
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello;sleep 2;echo world
        image: busybox
        name: echojob
        resources: {}
      restartPolicy: Never
status: {}
