apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: echojob
spec:
  completions: 4
  parallelism: 3
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo hello;sleep 10;echo world
        image: busybox
        name: echojob
        resources: {}
      restartPolicy: Never
status: {}
