apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: status-check
spec:
  startingDeadlineSeconds: 15
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: status-check
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date;echo "Check from k3s"
            image: busybox
            name: status-check
            resources: {}
          restartPolicy: Never
  schedule: '*/1 * * * *'
status: {}
