apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: time-limit
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: time-limit
    spec:
      activeDeadlineSeconds: 10
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; sleep 11; echo Check k3s cluster; date
            image: busybox
            name: time-limit
            resources: {}
          restartPolicy: Never
  schedule: '* * * * *'
status: {}
